# Generated by Django 2.2 on 2020-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='points',
            new_name='points_distribution',
        ),
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(),
        ),
    ]
