# Generated by Django 2.2 on 2020-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200415_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom_checker',
            field=models.BooleanField(default=False),
        ),
    ]
