# Generated by Django 2.2 on 2020-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_question_custom_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
